// Ini adalah simulasi data halaman.
// Dalam aplikasi nyata, data ini akan diambil dari database.
let pages = [
  {
    id: 1,
    title: "Beranda",
    slug: "beranda",
    hero_title: "CV Sumber Alam Raya",
    homepage_about_section_text: "CV Sumber Alam Raya adalah perusahaan manufaktur berbahan dasar besi yang melayani berbagai kebutuhan industri, mulai dari otomotif, konstruksi, hingga pengadaan barang umum.",
    homepage_services_section_text: "CV Sumber Alam Raya adalah perusahaan manufaktur yang berbasis di Tegal, Jawa Tengah.",
    body: "Isi utama halaman beranda.",
    contact_overlay_text: null,
    contact_title: null,
    contact_phone: null,
    contact_location_title: null,
    contact_location_body: null,
    contact_email_title: null,
    contact_email_address: null,
    contact_whatsapp_number: null,
    vision_title: null,
    vision_body: null,
    mission_title: null,
    mission_body: null,
    excellence_title: null,
    main_intro_body: null,
    service_1_title: null, service_1_body: null,
    service_2_title: null, service_2_body: null,
    service_3_title: null, service_3_body: null,
    gallery_intro_body: null,
    faq_main_title: null,
    faq_1_question: null, faq_1_answer: null,
    faq_2_question: null, faq_2_answer: null,
    faq_3_question: null, faq_3_answer: null,
    faq_4_question: null, faq_4_answer: null,
    faq_5_question: null, faq_5_answer: null,
  },
  {
    id: 2,
    title: "Tentang Kami",
    slug: "tentang",
    hero_title: null,
    homepage_about_section_text: null,
    homepage_services_section_text: null,
    body: "CV Sumber Alam Raya adalah perusahaan manufaktur yang berbasis di Tegal, Jawa Tengah. Kami bergerak di bidang pengolahan besi...",
    contact_overlay_text: null,
    contact_title: null,
    contact_phone: null,
    contact_location_title: null,
    contact_location_body: null,
    contact_email_title: null,
    contact_email_address: null,
    contact_whatsapp_number: null,
    vision_title: "Visi",
    vision_body: "Membangun perusahaan yang profesional, berintegritas tinggi, inovatif dan berkelanjutan.",
    mission_title: "Misi",
    mission_body: "Menyediakan produk dan layanan unggulan, menjaga hubungan baik dengan pelanggan, serta berkontribusi positif terhadap industri dan masyarakat.",
    excellence_title: "Keunggulan Kami",
    main_intro_body: null,
    service_1_title: null, service_1_body: null,
    service_2_title: null, service_2_body: null,
    service_3_title: null, service_3_body: null,
    gallery_intro_body: null,
    faq_main_title: null,
    faq_1_question: null, faq_1_answer: null,
    faq_2_question: null, faq_2_answer: null,
    faq_3_question: null, faq_3_answer: null,
    faq_4_question: null, faq_4_answer: null,
    faq_5_question: null, faq_5_answer: null,
  },
  {
    id: 3,
    title: "Layanan Kami",
    slug: "layanan",
    hero_title: null,
    homepage_about_section_text: null,
    homepage_services_section_text: null,
    body: "Dalam menjalankan usahanya di bidang manufaktur berbasis besi, CV Sumber Alam Raya berkomitmen untuk memberikan layanan...",
    contact_overlay_text: null,
    contact_title: null,
    contact_phone: null,
    contact_location_title: null,
    contact_location_body: null,
    contact_email_title: null,
    contact_email_address: null,
    contact_whatsapp_number: null,
    vision_title: null,
    vision_body: null,
    mission_title: null,
    mission_body: null,
    excellence_title: null,
    main_intro_body: "Dalam menjalankan usahanya di bidang manufaktur berbasis besi, CV Sumber Alam Raya berkomitmen untuk memberikan layanan yang profesional...",
    service_1_title: "Jasa Fabrikasi Besi Custom",
    service_1_body: "CV Sumber Alam Raya menyediakan layanan pengolahan bahan baku besi menjadi produk akhir sesuai permintaan pelanggan...",
    service_2_title: "Produksi Ornamen dan Komponen Besi",
    service_2_body: "Menyediakan komponen otomotif (seperti knalpot motor) serta ornamen besi untuk kebutuhan konstruksi dan dekorasi...",
    service_3_title: "Pengadaan Barang Berbahan Dasar Besi",
    service_3_body: "Layanan penyediaan produk berbasis besi untuk sektor industri, baik dalam skala kecil hingga menengah...",
    gallery_intro_body: null,
    faq_main_title: null,
    faq_1_question: null, faq_1_answer: null,
    faq_2_question: null, faq_2_answer: null,
    faq_3_question: null, faq_3_answer: null,
    faq_4_question: null, faq_4_answer: null,
    faq_5_question: null, faq_5_answer: null,
  },
  {
    id: 4,
    title: "Galeri Kami",
    slug: "galeri",
    hero_title: null,
    homepage_about_section_text: null,
    homepage_services_section_text: null,
    body: "Dokumentasi visual dari setiap proses dan hasil karya kami mencerminkan komitmen terhadap kualitas dan ketelitian.",
    contact_overlay_text: null,
    contact_title: null,
    contact_phone: null,
    contact_location_title: null,
    contact_location_body: null,
    contact_email_title: null,
    contact_email_address: null,
    contact_whatsapp_number: null,
    vision_title: null,
    vision_body: null,
    mission_title: null,
    mission_body: null,
    excellence_title: null,
    main_intro_body: null,
    service_1_title: null, service_1_body: null,
    service_2_title: null, service_2_body: null,
    service_3_title: null, service_3_body: null,
    gallery_intro_body: "Dokumentasi visual dari setiap proses dan hasil karya kami mencerminkan komitmen terhadap kualitas dan ketelitian...",
    faq_main_title: null,
    faq_1_question: null, faq_1_answer: null,
    faq_2_question: null, faq_2_answer: null,
    faq_3_question: null, faq_3_answer: null,
    faq_4_question: null, faq_4_answer: null,
    faq_5_question: null, faq_5_answer: null,
  },
  {
    id: 5,
    title: "Kontak Kami",
    slug: "kontak",
    hero_title: null,
    homepage_about_section_text: null,
    homepage_services_section_text: null,
    body: "", // Halaman kontak tidak memiliki 'body' utama tapi punya field spesifik
    contact_overlay_text: "Kepuasan Anda Tujuan Kami",
    contact_title: "Kontak Kami",
    contact_phone: "+62 895 0479 8167",
    contact_location_title: "Kunjungi kami",
    contact_location_body: "Desa Bengledukuh, Bengle, Kec. Talang, Kabupaten Tegal, Jawa Tengah 52193",
    contact_email_title: "Email",
    contact_email_address: "sumberalam423@gmail.com",
    contact_whatsapp_number: "+6287801319313",
    vision_title: null,
    vision_body: null,
    mission_title: null,
    mission_body: null,
    excellence_title: null,
    main_intro_body: null,
    service_1_title: null, service_1_body: null,
    service_2_title: null, service_2_body: null,
    service_3_title: null, service_3_body: null,
    gallery_intro_body: null,
    faq_main_title: null,
    faq_1_question: null, faq_1_answer: null,
    faq_2_question: null, faq_2_answer: null,
    faq_3_question: null, faq_3_answer: null,
    faq_4_question: null, faq_4_answer: null,
    faq_5_question: null, faq_5_answer: null,
  },
  {
    id: 6,
    title: "FAQ",
    slug: "faq",
    hero_title: null,
    homepage_about_section_text: null,
    homepage_services_section_text: null,
    body: null,
    contact_overlay_text: null,
    contact_title: null,
    contact_phone: null,
    contact_location_title: null,
    contact_location_body: null,
    contact_email_title: null,
    contact_email_address: null,
    contact_whatsapp_number: null,
    vision_title: null,
    vision_body: null,
    mission_title: null,
    mission_body: null,
    excellence_title: null,
    main_intro_body: null,
    service_1_title: null, service_1_body: null,
    service_2_title: null, service_2_body: null,
    service_3_title: null, service_3_body: null,
    gallery_intro_body: null,
    faq_main_title: "Frequently Asked Question",
    faq_1_question: "Produk apa saja yang diproduksi oleh CV Sumber Alam Raya?",
    faq_1_answer: "Kami memproduksi beragam produk berbahan dasar besi seperti tangki oli hidrolik, ornamen pagar, aksesoris knalpot, pipa hollow, dan komponen kendaraan lainnya.",
    faq_2_question: "Apakah bisa pesan produk custom sesuai kebutuhan?",
    faq_2_answer: "Ya, kami menerima pemesanan produk sesuai desain atau spesifikasi dari pelanggan.",
    faq_3_question: "Bagaimana cara melakukan pemesanan?",
    faq_3_answer: "Anda dapat menghubungi kami melalui WhatsApp pada website ini. Tim kami akan membantu Anda dalam proses pemesanan.",
    faq_4_question: "Berapa lama waktu produksi dan pengiriman?",
    faq_4_answer: "Waktu produksi dan pengiriman bervariasi tergantung kompleksitas dan lokasi. Umumnya 3–7 hari kerja.",
    faq_5_question: "Apakah bisa melakukan kerja sama jangka panjang?",
    faq_5_answer: "Tentu saja! Kami terbuka untuk kerja sama jangka panjang dengan perusahaan, instansi, atau mitra distribusi.",
  },
  // Tambahkan halaman lain seperti 'produk' jika Anda ingin mengelola detailnya di sini
];

export const getPages = () => pages;

export const findPageById = (id) => pages.find(p => p.id === parseInt(id));

export const findPageBySlug = (slug) => pages.find(p => p.slug === slug);


export const updatePage = (id, updatedFields) => {
  const index = pages.findIndex(p => p.id === parseInt(id));
  if (index !== -1) {
    pages[index] = { ...pages[index], ...updatedFields };
    return pages[index];
  }
  return null;
};

export const createPage = (newPage) => {
  const newId = Math.max(...pages.map(p => p.id)) + 1;
  const page = { id: newId, ...newPage };
  pages.push(page);
  return page;
};

export const deletePage = (id) => {
  const initialLength = pages.length;
  pages = pages.filter(p => p.id !== parseInt(id));
  return pages.length < initialLength; // Return true if a page was deleted
};